Repository olofeldre/DD2480-group1-assignment2, pull requests merged in 2021-02, with the labels that each got.

#2 feature #1 Start the project structure with maven and add minimal CI
  CI/pom.xml
  CI/src/main/java/group1/ContinuousIntegrationServer.java
  CI/src/main/java/group1/Main.java
Labels: enhancement

#16 Update README.md
  README.md
Labels: documentation

#6 Feature #3 Create a Firebase backend and a Firestore database
  .firebaserc
  .gitignore
  firebase.json
  firestore.indexes.json
  firestore.rules
  public/404.html
  public/index.html
Labels: enhancement

#14 Feature #13 Email notification functionality
  .gitignore
  CI/pom.xml
  CI/src/main/java/group1/Email.java
  CI/src/test/java/group1/EmailTest.java
  CI/src/test/resources/t1.txt
Labels: enhancement

#23 Issue10 clone repo
  .gitignore
  CI/pom.xml
  CI/src/main/java/group1/ValidateRepo.java
  CI/src/test/java/group1/ValidateRepoTest.java
Labels: enhancement

#24 Feature #18 Html page with unique URL
  index.html
  public/buildpage.html
  public/index.html
Labels: enhancement

#26 Issue21 compile repo
  CI/src/main/java/group1/ValidateRepo.java
  CI/src/test/java/group1/ValidateRepoTest.java
Labels: enhancement

#27 Issue22 run tests
  CI/src/main/java/group1/ValidateRepo.java
  CI/src/test/java/group1/ValidateRepoTest.java
Labels: enhancement

#31 feature #30 Send email upon recieving data from the webhook
  CI/src/main/java/group1/ContinuousIntegrationServer.java
Labels: enhancement

#36 fix #35 Web page does not display data from database
  public/index.html
Labels: bug

#33 feature #11 Make port number a choice at launch
  CI/src/main/java/group1/Main.java
Labels: enhancement

#34 feature #19 Update database from backend
  .gitignore
  CI/pom.xml
  CI/src/main/java/group1/ContinuousIntegrationServer.java
  CI/src/main/java/group1/InitFirebase.java
  CI/src/main/java/group1/Main.java
  CI/src/main/java/group1/ValidateRepo.java
  CI/src/test/java/group1/EmailTest.java
Labels: enhancement

#41 Feature #38 Sort the list of build results in the frontend
  public/index.html
Labels: enhancement
